'use client';

import {useEffect,useState} from 'react';

type Record={id:number;vehicleLabel:string;driver:string;route?:string|null;odometer:number;amountCents:number;createdAt:string;items:{kind:string;quantity:number;amountCents:number}[]};
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value/100);
const date=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Bahia'}).format(new Date(value));

export default function MeusAbastecimentos(){
 const [records,setRecords]=useState<Record[]>([]),[message,setMessage]=useState('Carregando seus abastecimentos...');
 useEffect(()=>{void fetch('/api/fueling?days=30',{cache:'no-store'}).then(async response=>{const data:any=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível carregar os abastecimentos.');setRecords(data.records||[]);setMessage('')}).catch(error=>setMessage(error instanceof Error?error.message:'Não foi possível carregar os abastecimentos.'))},[]);
 return <main className="min-h-screen bg-[#f3f6f9] p-5"><div className="mx-auto max-w-xl"><button type="button" onClick={()=>window.location.assign('/')} className="mb-5 h-12 rounded-xl border-2 border-slate-500 bg-white px-5 text-lg font-bold text-slate-700">Página inicial</button><header className="rounded-3xl bg-[#b3262b] p-5 text-white shadow"><div className="flex items-center gap-3"><img src="/icon.png" alt="SD Tour" className="h-14 w-14 rounded-2xl bg-white p-1"/><div><p className="text-sm font-bold uppercase tracking-[.12em]">SD Tour</p><h1 className="text-3xl font-extrabold">Meus abastecimentos</h1></div></div><p className="mt-3 text-lg text-white/90">Somente os seus registros dos últimos 30 dias.</p></header>{!message&&records.length===0?<p className="mt-6 rounded-2xl bg-white p-5 text-lg text-slate-600 shadow">Nenhum abastecimento seu foi registrado nos últimos 30 dias.</p>:<div className="mt-6 space-y-4">{records.map(record=><article key={record.id} className="rounded-2xl bg-white p-5 shadow"><p className="text-lg text-slate-600">{date(record.createdAt)}</p><p className="mt-2 text-xl font-extrabold text-[#102b43]">{record.vehicleLabel}</p><p className="mt-2 text-lg"><strong>Roteiro:</strong> {record.route||'Não informado'}</p><p className="mt-2 text-lg"><strong>Quilometragem:</strong> {Number(record.odometer).toLocaleString('pt-BR')} km</p><div className="mt-3 border-t pt-3 text-lg">{record.items.map((item,index)=><p key={index}>{item.kind}: {Number(item.quantity).toLocaleString('pt-BR')} · {money(item.amountCents)}</p>)}</div><p className="mt-3 text-xl font-extrabold text-[#178045]">Total: {money(record.amountCents)}</p></article>)}</div>}{message&&<p role="status" className="mt-6 rounded-2xl bg-sky-50 p-5 text-lg text-slate-700">{message}</p>}</div></main>
}
