import {env} from 'cloudflare:workers';
import {isAdmin} from '../../admin-auth';

const dateOk=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value);
type Context={params:Promise<{id:string}>};
type TripInput={vehicleId:number;departureDate:string;arrivalDate:string;route:string;totalKm:number;associatedUserIds?:number[];allowConflicts?:boolean};
function valid(input:TripInput){return Number.isInteger(input.vehicleId)&&dateOk(input.departureDate)&&dateOk(input.arrivalDate)&&input.arrivalDate>=input.departureDate&&typeof input.route==='string'&&!!input.route.trim()&&input.route.trim().length<=300&&Number.isSafeInteger(input.totalKm)&&input.totalKm>0&&Array.isArray(input.associatedUserIds)&&input.associatedUserIds.length<=3&&input.associatedUserIds.every(Number.isSafeInteger)}
async function driverConflict(driverIds:number[],departureDate:string,arrivalDate:string,id:number){for(const driverId of driverIds){const row=await env.DB!.prepare('SELECT t.id FROM trips t JOIN trip_users tu ON tu.trip_id=t.id WHERE tu.user_id=? AND t.id<>? AND COALESCE(t.departure_date,t.travel_date)<=? AND COALESCE(t.arrival_date,t.travel_date)>=? LIMIT 1').bind(driverId,id,arrivalDate,departureDate).first();if(row)return true}return false}

export async function PUT(req:Request,{params}:Context){if(!await isAdmin(req))return Response.json({error:'Acesso restrito.'},{status:403});try{const id=Number((await params).id),input=await req.json() as TripInput;if(!Number.isSafeInteger(id)||!valid(input))return Response.json({error:'Confira os dados da viagem e selecione no máximo três motoristas.'},{status:400});const selected=[...new Set(input.associatedUserIds||[])];const [vehicleBusy,driverBusy]=await Promise.all([env.DB!.prepare('SELECT id FROM trips WHERE vehicle_id=? AND id<>? AND COALESCE(departure_date,travel_date)<=? AND COALESCE(arrival_date,travel_date)>=? LIMIT 1').bind(input.vehicleId,id,input.arrivalDate,input.departureDate).first(),driverConflict(selected,input.departureDate,input.arrivalDate,id)]);if((vehicleBusy||driverBusy)&&!input.allowConflicts)return Response.json({error:'Já existe viagem para este carro ou motorista no período. Confirme a compatibilidade de horário antes de salvar.',conflicts:{vehicle:!!vehicleBusy,driver:driverBusy}},{status:409});const automatic=await env.DB!.prepare("SELECT id FROM app_users WHERE active=1 AND group_name IN ('adm','gerencia')").all<{id:number}>();const userIds=[...new Set([...selected,...automatic.results.map(user=>user.id)])];await env.DB!.batch([env.DB!.prepare('UPDATE trips SET vehicle_id=?,travel_date=?,departure_date=?,arrival_date=?,route=?,total_km=? WHERE id=?').bind(input.vehicleId,input.departureDate,input.departureDate,input.arrivalDate,input.route.trim(),input.totalKm,id),env.DB!.prepare('DELETE FROM trip_users WHERE trip_id=?').bind(id),...userIds.map(userId=>env.DB!.prepare('INSERT INTO trip_users (trip_id,user_id) VALUES (?,?)').bind(id,userId))]);return Response.json({updated:true})}catch{return Response.json({error:'Não foi possível editar a viagem.'},{status:503})}}
export async function DELETE(req:Request,{params}:Context){if(!await isAdmin(req))return Response.json({error:'Acesso restrito.'},{status:403});try{const id=Number((await params).id);if(!Number.isSafeInteger(id))return Response.json({error:'Viagem inválida.'},{status:400});const trip=await env.DB!.prepare('SELECT id FROM trips WHERE id=?').bind(id).first();if(!trip)return Response.json({error:'Esta viagem já não existe.'},{status:404});const notices=await env.DB!.prepare("SELECT id FROM fuel_requests WHERE trip_id=?").bind(id).all<{id:number}>();await env.DB!.batch([env.DB!.prepare('DELETE FROM trip_users WHERE trip_id=?').bind(id),...notices.results.map(item=>env.DB!.prepare('DELETE FROM app_notifications WHERE href=?').bind(`/autorizacoes?pedido=${item.id}`)),env.DB!.prepare('DELETE FROM fuel_requests WHERE trip_id=?').bind(id),env.DB!.prepare('DELETE FROM trips WHERE id=?').bind(id)]);return Response.json({deleted:true});}catch{return Response.json({error:'Não foi possível apagar a viagem.'},{status:503})}}
