'use client';

import {useEffect,useState} from 'react';

type User={id:number;name:string;username:string};
export default function Desenvolvedor(){
 const [code,setCode]=useState(''),[users,setUsers]=useState<User[]>([]),[userId,setUserId]=useState(''),[password,setPassword]=useState('1234'),[forceChange,setForceChange]=useState(true),[unlocked,setUnlocked]=useState(false),[message,setMessage]=useState('');
 async function unlock(event:React.FormEvent){event.preventDefault();const response=await fetch('/api/users',{cache:'no-store'}),data:any=await response.json();if(!response.ok){setMessage('Apenas o administrador principal pode acessar esta área.');return}if(code!=='0815'){setMessage('Senha de desenvolvedor incorreta.');return}setUsers(data.users||[]);setUnlocked(true);setMessage('Área de desenvolvedor liberada.');}
 async function reset(event:React.FormEvent){event.preventDefault();if(!/^\d{4}$/.test(password)){setMessage('A senha deve conter 4 números.');return}const response=await fetch('/api/admin/developer-password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({developerCode:code,userId:Number(userId),password,forceChange})}),data:any=await response.json();setMessage(response.ok?'Senha atualizada com sucesso.':data.error||'Não foi possível atualizar a senha.');}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><button type="button" onClick={()=>window.location.assign('/admin/configuracoes')} className="mb-5 min-h-12 rounded-xl border px-5 py-2 text-lg font-bold">Voltar para Configurações</button><section className="rounded-3xl bg-white p-6 shadow"><h1 className="text-3xl font-extrabold">Desenvolvedor</h1>{!unlocked?<><p className="mt-2 text-lg text-slate-600">Área restrita para administração de senhas.</p><form onSubmit={unlock} className="mt-6 space-y-4"><input autoFocus type="password" inputMode="numeric" maxLength={4} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,'').slice(0,4))} placeholder="Senha de desenvolvedor" className="h-14 w-full rounded-xl border p-3 text-xl"/><button className="h-14 w-full rounded-xl bg-[#46515d] text-xl font-bold text-white">Entrar</button></form></>:<form onSubmit={reset} className="mt-6 space-y-4"><label className="block text-lg font-bold">Usuário<select required value={userId} onChange={event=>setUserId(event.target.value)} className="mt-2 h-14 w-full rounded-xl border bg-white p-3 text-lg"><option value="">Escolha o usuário</option>{users.map(user=><option key={user.id} value={user.id}>{user.name} · {user.username}</option>)}</select></label><label className="block text-lg font-bold">Nova senha<input inputMode="numeric" maxLength={4} value={password} onChange={event=>setPassword(event.target.value.replace(/\D/g,'').slice(0,4))} className="mt-2 h-14 w-full rounded-xl border p-3 text-xl"/></label><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-lg"><input checked={forceChange} onChange={event=>setForceChange(event.target.checked)} type="checkbox" className="h-5 w-5"/>Exigir que o usuário troque esta senha no próximo acesso</label><button className="h-14 w-full rounded-xl bg-[#b3262b] text-xl font-bold text-white">Salvar senha</button></form>}{message&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{message}</p>}</section></div></main>;
}
