'use client';

import {useEffect,useState} from 'react';

type Trip={id:number;vehicleLabel:string;departureDate:string;arrivalDate:string;route:string};
type Detail={liters:string;km:string;paymentStatus:'total'|'parcial'|'nao_pago';balance:string};
const decimal=(value:string)=>{const clean=value.trim();return Number(clean.includes(',')?clean.replace(/\./g,'').replace(',','.'):clean)};
const paymentVisual=(status:Detail['paymentStatus'])=>status==='total'?{icon:'✓',label:'Totalmente paga',className:'bg-green-50 text-[#178045]'}:status==='parcial'?{icon:'?',label:'Parcialmente paga',className:'bg-amber-50 text-[#a16207]'}:{icon:'×',label:'Não paga',className:'bg-red-50 text-[#b3262b]'};

export default function DetalhesSolicitacao(){
 const [trips,setTrips]=useState<Trip[]>([]),[details,setDetails]=useState<Record<number,Detail>>({}),[message,setMessage]=useState('Carregando roteiros...');
 useEffect(()=>{void (async()=>{const selected=new URLSearchParams(window.location.search).getAll('trip').map(Number).filter(Number.isInteger);if(!selected.length){window.location.replace('/solicitar-abastecimento');return}try{const response=await fetch('/api/trips',{cache:'no-store'}),data:any=await response.json();if(!response.ok){setMessage(data.error||'Não foi possível carregar os roteiros.');return}const chosen=(data.trips||[]).filter((trip:Trip)=>selected.includes(trip.id));setTrips(chosen);setDetails(Object.fromEntries(chosen.map((trip:Trip)=>[trip.id,{liters:'',km:'',paymentStatus:'nao_pago',balance:''}])));setMessage('')}catch{setMessage('Não foi possível carregar os roteiros.')}})()},[]);
 function continueToContacts(){if(!trips.length)return;for(const trip of trips){const detail=details[trip.id];if(!Number.isFinite(decimal(detail?.liters||''))||decimal(detail.liters)<=0||!Number.isSafeInteger(Number(detail?.km))||Number(detail.km)<0){setMessage('Informe litros e KM válidos para todos os roteiros selecionados.');return}if(detail.paymentStatus!=='total'&&(!Number.isFinite(decimal(detail.balance||''))||decimal(detail.balance)<=0)){setMessage('Informe o valor que falta pagar quando a viagem não estiver totalmente paga.');return}}const params=new URLSearchParams();trips.forEach(trip=>{const detail=details[trip.id];params.append('trip',String(trip.id));params.append('liters',detail.liters);params.append('km',detail.km);params.append('payment',detail.paymentStatus);params.append('balance',detail.balance)});window.location.assign('/solicitar-abastecimento/destinatarios?'+params.toString())}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><button type="button" onClick={()=>window.history.back()} className="mb-5 h-14 w-full rounded-xl border-2 border-slate-500 px-3 text-lg font-bold text-slate-700">Voltar para seleção</button><section className="rounded-3xl border-2 border-[#096a9b] bg-white p-6 shadow"><h1 className="text-3xl font-bold">Litros, KM e pagamento</h1><p className="mt-3 text-lg text-slate-600">Informe os dados de cada roteiro selecionado.</p><div className="mt-5 space-y-4">{trips.map(trip=>{const detail=details[trip.id]||{liters:'',km:'',paymentStatus:'nao_pago' as const,balance:''};const visual=paymentVisual(detail.paymentStatus);return <div key={trip.id} className="rounded-2xl bg-slate-50 p-4"><p className="text-xl font-bold">{trip.vehicleLabel}</p><p className="mt-1 text-lg">{trip.route}</p><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-base font-bold">Litros<input inputMode="decimal" value={detail.liters} onChange={event=>setDetails(all=>({...all,[trip.id]:{...detail,liters:event.target.value}}))} className="mt-2 h-12 w-full rounded-xl border p-2 text-lg"/></label><label className="text-base font-bold">KM do trajeto<input inputMode="numeric" value={detail.km} onChange={event=>setDetails(all=>({...all,[trip.id]:{...detail,km:event.target.value}}))} className="mt-2 h-12 w-full rounded-xl border p-2 text-lg"/></label></div><label className="mt-4 block text-base font-bold">Situação de pagamento<select value={detail.paymentStatus} onChange={event=>setDetails(all=>({...all,[trip.id]:{...detail,paymentStatus:event.target.value as Detail['paymentStatus'],balance:event.target.value==='total'?'':detail.balance}}))} className="mt-2 h-12 w-full rounded-xl border bg-white p-2 text-lg"><option value="total">Totalmente paga</option><option value="parcial">Parcialmente paga</option><option value="nao_pago">Não paga</option></select></label><p className={`mt-3 inline-flex items-center gap-2 rounded-xl px-3 py-2 text-base font-bold ${visual.className}`}><span className="grid h-6 w-6 place-items-center rounded-full border-2 border-current">{visual.icon}</span>{visual.label}</p>{detail.paymentStatus!=='total'&&<label className="mt-4 block text-base font-bold">Valor que falta pagar (R$)<input inputMode="decimal" value={detail.balance} onChange={event=>setDetails(all=>({...all,[trip.id]:{...detail,balance:event.target.value}}))} className="mt-2 h-12 w-full rounded-xl border p-2 text-lg" placeholder="Ex.: 350,00"/></label>}</div>})}</div><button type="button" onClick={continueToContacts} className="mt-6 min-h-14 h-auto w-full rounded-xl bg-[#178045] px-4 py-2 text-lg font-bold leading-tight text-white sm:text-xl">Escolher destinatários</button></section>{message&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{message}</p>}</div></main>
}
