'use client';
import {useEffect,useState} from 'react';
type Trip={id:number;vehicleId:number;vehicleLabel:string;departureDate:string;arrivalDate:string;route:string;userIds:number[]};
type Contact={id:number;name:string;phone:string};
type AppUser={id:number;name:string;roles:string;groupName:'motorista'|'adm'|'gerencia'};
const formatDate=(date:string)=>date.split('-').reverse().join('/');

export default function AdminClient(){
 const today=new Date().toISOString().slice(0,10);
 const [cars,setCars]=useState<any[]>([]),[trips,setTrips]=useState<Trip[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[users,setUsers]=useState<AppUser[]>([]);
 const [car,setCar]=useState(''),[departureDate,setDepartureDate]=useState(today),[arrivalDate,setArrivalDate]=useState(today),[route,setRoute]=useState(''),[editing,setEditing]=useState<number|null>(null),[confirmId,setConfirmId]=useState<number|null>(null),[msg,setMsg]=useState('');
 const [showContacts,setShowContacts]=useState(false),[contactName,setContactName]=useState(''),[contactPhone,setContactPhone]=useState('');
 async function load(){const [a,b,c,d]=await Promise.all([fetch('/api/vehicles',{cache:'no-store'}),fetch('/api/trips',{cache:'no-store'}),fetch('/api/contacts',{cache:'no-store'}),fetch('/api/users',{cache:'no-store'})]);const va:any=await a.json(),tb:any=await b.json(),ct:any=await c.json(),us:any=await d.json();setCars(va.vehicles||[]);if(!b.ok)throw Error(tb.error);setTrips(tb.trips||[]);if(c.ok)setContacts(ct.contacts||[]);if(d.ok)setUsers(us.users||[])}
 useEffect(()=>{void (async()=>{const setup=await fetch('/api/system/setup',{method:'POST'}),x:any=await setup.json();if(!setup.ok)throw Error(x.error);await load()})().catch((e:Error)=>setMsg(e.message||'Não foi possível carregar os dados.'))},[]);
 function clear(){setCar('');setDepartureDate(today);setArrivalDate(today);setRoute('');setEditing(null);setConfirmId(null)}
 async function save(e:React.FormEvent){e.preventDefault();const associatedUserIds=new FormData(e.currentTarget).getAll('associatedUser').map(Number).filter(Number.isSafeInteger);const wasEditing=editing!==null,r=await fetch(editing?'/api/trips/'+editing:'/api/trips',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicleId:Number(car),departureDate,arrivalDate,route,associatedUserIds})}),x:any=await r.json();if(!r.ok)return setMsg(x.error||'Não foi possível salvar.');clear();await load();setMsg(wasEditing?'Viagem atualizada.':'Viagem lançada e salva na lista abaixo.')}
 function edit(t:Trip){setEditing(t.id);setCar(String(t.vehicleId));setDepartureDate(t.departureDate);setArrivalDate(t.arrivalDate);setRoute(t.route);setMsg('Editando a viagem selecionada.');window.scrollTo({top:0,behavior:'smooth'})}
 async function remove(t:Trip){const r=await fetch('/api/trips/'+t.id,{method:'DELETE',cache:'no-store'}),x:any=await r.json().catch(()=>({}));if(!r.ok)return setMsg(x.error||'Não foi possível apagar.');setTrips(list=>list.filter(i=>i.id!==t.id));setConfirmId(null);setMsg('Viagem apagada e removida da lista.')}
 async function saveContact(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:contactName,phone:contactPhone})}),x:any=await r.json();if(!r.ok)return setMsg(x.error||'Não foi possível cadastrar o contato.');setContacts(list=>[...list,x.contact]);setContactName('');setContactPhone('');setMsg('Contato WhatsApp cadastrado.')}
 async function leaveAdmin(){await fetch('/api/admin-session',{method:'DELETE'});window.location.assign('/')}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><div className="mb-5 grid grid-cols-1 gap-3 sm:grid-cols-2"><button type="button" onClick={()=>window.location.assign('/solicitar-abastecimento')} className="h-14 rounded-xl bg-[#096a9b] px-3 text-base font-bold text-white sm:text-lg">Solicitar abastecimento</button><button type="button" onClick={()=>window.location.assign('/admin/configuracoes')} className="h-14 rounded-xl border-2 border-[#096a9b] px-3 text-base font-bold text-[#096a9b] sm:text-lg">⚙ Configurações</button><button type="button" onClick={()=>window.location.assign('/autorizacoes')} className="min-h-20 h-auto rounded-xl bg-[#b3262b] px-3 py-3 text-xl font-extrabold leading-tight text-white sm:text-2xl">⛽ AUTORIZAR</button><button type="button" onClick={()=>window.location.assign('/pedidos?status=pending')} className="h-14 rounded-xl bg-[#e7b629] px-3 text-base font-bold text-[#2c2509] sm:text-lg">Pedidos pendentes</button><button type="button" onClick={()=>window.location.assign('/pedidos?status=authorized')} className="h-14 rounded-xl bg-[#178045] px-3 text-base font-bold text-white sm:text-lg">Já autorizados</button><button type="button" onClick={()=>void leaveAdmin()} className="h-14 rounded-xl border-2 border-slate-500 px-3 text-base font-bold text-slate-700 sm:col-span-2 sm:text-lg">Sair para a página inicial</button></div>
 {showContacts&&<section className="mb-7 rounded-3xl bg-white p-6 shadow"><h2 className="text-2xl font-bold">Contatos para WhatsApp</h2><form onSubmit={saveContact} className="mt-5 grid gap-3"><input required value={contactName} onChange={e=>setContactName(e.target.value)} placeholder="Nome do contato" className="h-14 rounded-xl border p-3 text-lg"/><input required inputMode="tel" value={contactPhone} onChange={e=>setContactPhone(e.target.value)} placeholder="WhatsApp com DDD" className="h-14 rounded-xl border p-3 text-lg"/><button className="h-12 rounded-xl bg-[#178045] text-lg font-bold text-white">Cadastrar contato</button></form>{contacts.length>0&&<div className="mt-5 space-y-2">{contacts.map(c=><p key={c.id} className="rounded-xl bg-slate-50 p-3 text-lg"><strong>{c.name}</strong> · {c.phone}</p>)}</div>}</section>}
 <section className="rounded-3xl bg-white p-7 shadow"><h1 className="text-3xl font-bold">{editing?'Editar viagem':'Lançar viagem'}</h1><p className="mt-2 text-lg">Área exclusiva do administrador.</p><form onSubmit={save} className="mt-6 space-y-5"><label className="block text-lg font-bold">Veículo<select value={car} onChange={e=>setCar(e.target.value)} required className="mt-2 h-16 w-full rounded-xl border p-3 text-2xl"><option value="">Selecione</option>{cars.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><div className="grid grid-cols-2 gap-4"><label className="block text-lg font-bold">Saída<input type="date" value={departureDate} onChange={e=>{setDepartureDate(e.target.value);if(arrivalDate<e.target.value)setArrivalDate(e.target.value)}} className="mt-2 h-16 w-full rounded-xl border p-3 text-lg"/></label><label className="block text-lg font-bold">Chegada<input type="date" min={departureDate} value={arrivalDate} onChange={e=>setArrivalDate(e.target.value)} className="mt-2 h-16 w-full rounded-xl border p-3 text-lg"/></label></div><label className="block text-lg font-bold">Roteiro<textarea value={route} onChange={e=>setRoute(e.target.value)} required maxLength={300} className="mt-2 min-h-32 w-full rounded-xl border p-3 text-2xl"/></label><fieldset className="rounded-2xl border p-4"><legend className="px-2 text-lg font-bold">Motoristas associados à viagem</legend><p className="mb-3 text-base text-slate-600">Adm e Gerência são associados automaticamente. Selecione apenas os motoristas deste roteiro.</p>{users.filter(u=>u.groupName==='motorista').length===0?<p className="text-base">Cadastre motoristas em Configurações.</p>:<div className="space-y-2">{users.filter(u=>u.groupName==='motorista').map(u=><label key={u.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-lg"><input name="associatedUser" type="checkbox" value={u.id} defaultChecked={editing!==null&&trips.find(t=>t.id===editing)?.userIds.includes(u.id)} className="h-5 w-5 accent-[#178045]"/><span>{u.name}</span></label>)}</div>}</fieldset><div className="flex gap-3"><button className="h-14 flex-1 rounded-xl bg-[#178045] text-xl font-bold text-white">{editing?'Salvar alterações':'Salvar viagem'}</button>{editing&&<button type="button" onClick={()=>{clear();setMsg('Edição cancelada. O formulário foi limpo.')}} className="h-14 rounded-xl border px-4 text-lg">Cancelar</button>}</div></form>{msg&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{msg}</p>}</section>
 <section className="mt-7"><h2 className="mb-2 text-2xl font-bold">Viagens lançadas e salvas</h2>{trips.length===0?<p className="rounded-2xl bg-white p-5 text-lg">Nenhuma viagem salva.</p>:<div className="space-y-4">{trips.map(t=><article key={t.id} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xl font-bold">{t.vehicleLabel}</p><p className="mt-1 text-lg">{formatDate(t.departureDate)} até {formatDate(t.arrivalDate)}</p><p className="mt-2 text-lg text-slate-700">{t.route}</p>{confirmId===t.id?<div className="mt-5 rounded-xl border-2 border-[#b3262b] bg-red-50 p-4"><p className="text-lg font-bold text-[#7f1d1d]">Deseja apagar esta viagem?</p><div className="mt-4 flex gap-3"><button type="button" onClick={()=>void remove(t)} className="h-12 rounded-xl bg-[#b3262b] px-5 text-lg font-bold text-white">Confirmar apagar</button><button type="button" onClick={()=>setConfirmId(null)} className="h-12 rounded-xl border px-5 text-lg font-bold">Cancelar</button></div></div>:<div className="mt-5 flex gap-4"><button type="button" onClick={()=>edit(t)} className="h-12 rounded-xl bg-[#e7b629] px-5 text-lg font-bold text-[#2c2509]">Editar</button><button type="button" onClick={()=>setConfirmId(t.id)} className="h-12 rounded-xl bg-[#b3262b] px-5 text-lg font-bold text-white">Apagar</button></div>}</article>)}</div>}</section></div></main>
}
