'use client';

import {useEffect,useMemo,useState} from 'react';
type Trip={id:number;vehicleLabel:string;departureDate:string;arrivalDate:string;route:string};
type Contact={id:number;name:string};
const date=(value:string)=>value.split('-').reverse().join('/');
const decimal=(value:string)=>{const clean=value.trim();return Number(clean.includes(',')?clean.replace(/\./g,'').replace(',','.'):clean)};

export default function EnviarSolicitacao(){
 const [trips,setTrips]=useState<Trip[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[liters,setLiters]=useState<string[]>([]),[kms,setKms]=useState<string[]>([]),[payments,setPayments]=useState<string[]>([]),[balances,setBalances]=useState<string[]>([]),[message,setMessage]=useState('Preparando solicitação...'),[sending,setSending]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{void (async()=>{const params=new URLSearchParams(window.location.search),ids=params.getAll('trip').map(Number).filter(Number.isInteger),contactIds=params.getAll('contact').map(Number).filter(Number.isInteger);setLiters(params.getAll('liters'));setKms(params.getAll('km'));setPayments(params.getAll('payment'));setBalances(params.getAll('balance'));if(!ids.length){setMessage('Nenhuma viagem foi informada.');return}try{const [tripResponse,contactResponse]=await Promise.all([fetch('/api/trips',{cache:'no-store'}),fetch('/api/contacts',{cache:'no-store'})]);const tripData:any=await tripResponse.json(),contactData:any=await contactResponse.json();if(!tripResponse.ok){setMessage(tripData.error||'Não foi possível preparar a solicitação.');return}setTrips((tripData.trips||[]).filter((trip:Trip)=>ids.includes(trip.id)));if(contactResponse.ok)setContacts((contactData.contacts||[]).filter((contact:Contact)=>contactIds.includes(contact.id)));setMessage('')}catch{setMessage('Não foi possível preparar a solicitação.')}})()},[]);
 const text=useMemo(()=>{const lines=['*SOLICITAÇÃO DE ABASTECIMENTO*',''];trips.forEach((trip,index)=>{const payment=payments[index]==='total'?'Totalmente paga':payments[index]==='parcial'?'Parcialmente paga':'Não paga';lines.push(`${index+1}. *Carro:* ${trip.vehicleLabel}`,`*Roteiro:* ${trip.route}`,`*Período:* ${date(trip.departureDate)} a ${date(trip.arrivalDate)}`,`*Litros solicitados:* ${liters[index]||''} L`,`*KM previsto:* ${kms[index]||''} km`,`*Situação de pagamento:* ${payment}`,...(payment==='Totalmente paga'?[]:[`*Valor pendente:* R$ ${balances[index]||''}`]),'')});if(contacts.length)lines.push(`*Destinatários:* ${contacts.map(contact=>contact.name).join(', ')}`);return lines.join('\n')},[trips,contacts,liters,kms,payments,balances]);
 async function saveAndOpen(){if(sending||saved)return;setSending(true);try{const requests=trips.map((trip,index)=>({tripId:trip.id,liters:decimal(String(liters[index]||'')),routeKm:Number(kms[index]),paymentStatus:payments[index]||'nao_pago',outstandingCents:Math.round(decimal(String(balances[index]||'0'))*100)}));const r=await fetch('/api/fuel-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests})}),x:any=await r.json();if(!r.ok)throw Error(x.error||'Não foi possível salvar o pedido.');setSaved(true);window.location.assign('https://wa.me/?text='+encodeURIComponent(text));}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível salvar o pedido.')}finally{setSending(false)}}
 if(saved)return <main className="grid min-h-screen place-items-center bg-slate-50 p-5"><section className="max-w-xl rounded-3xl bg-white p-8 text-center shadow"><h1 className="text-3xl font-bold text-[#178045]">Pedido criado</h1><p className="mt-3 text-lg">O WhatsApp está sendo aberto com a mensagem de solicitação.</p><button onClick={()=>window.location.assign('/')} className="mt-6 h-14 rounded-xl border px-6 text-lg font-bold">Sair para a página inicial</button></section></main>;
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><button type="button" onClick={()=>window.history.back()} className="mb-5 h-14 w-full rounded-xl border-2 border-slate-500 px-3 text-lg font-bold text-slate-700">Voltar para destinatários</button><section className="rounded-3xl border-2 border-[#096a9b] bg-white p-6 shadow"><h1 className="text-3xl font-bold">Solicitação pronta</h1><p className="mt-3 text-lg text-slate-600">Ao continuar, o pedido fica Pendente de autorização e o WhatsApp abre uma única vez.</p><pre className="mt-5 whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 font-sans text-base">{text}</pre><button type="button" onClick={()=>void saveAndOpen()} disabled={!!message||!trips.length||sending} className="mt-5 min-h-14 h-auto w-full rounded-xl bg-[#178045] px-4 py-2 text-lg font-bold leading-tight text-white disabled:opacity-50 sm:text-xl">{sending?'Salvando pedido...':'Salvar pedido e abrir WhatsApp'}</button></section>{message&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{message}</p>}</div></main>
}
