'use client';

import {useEffect,useMemo,useState} from 'react';
type Trip={id:number;vehicleLabel:string;departureDate:string;arrivalDate:string;route:string};
type Contact={id:number;name:string};
const date=(value:string)=>value.split('-').reverse().join('/');

export default function EnviarSolicitacao(){
 const [trips,setTrips]=useState<Trip[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[liters,setLiters]=useState<string[]>([]),[kms,setKms]=useState<string[]>([]),[message,setMessage]=useState('Preparando solicitação...');
 useEffect(()=>{void (async()=>{const params=new URLSearchParams(window.location.search),ids=params.getAll('trip').map(Number).filter(Number.isInteger),contactIds=params.getAll('contact').map(Number).filter(Number.isInteger);setLiters(params.getAll('liters'));setKms(params.getAll('km'));if(!ids.length){setMessage('Nenhuma viagem foi informada.');return}try{const [tripResponse,contactResponse]=await Promise.all([fetch('/api/trips',{cache:'no-store'}),fetch('/api/contacts',{cache:'no-store'})]);const tripData:any=await tripResponse.json(),contactData:any=await contactResponse.json();if(!tripResponse.ok){setMessage(tripData.error||'Não foi possível preparar a solicitação.');return}setTrips((tripData.trips||[]).filter((trip:Trip)=>ids.includes(trip.id)));if(contactResponse.ok)setContacts((contactData.contacts||[]).filter((contact:Contact)=>contactIds.includes(contact.id)));setMessage('')}catch{setMessage('Não foi possível preparar a solicitação.')}})()},[]);
 const text=useMemo(()=>{const lines=['*SOLICITAÇÃO DE ABASTECIMENTO*',''];trips.forEach((trip,index)=>lines.push(`${index+1}. *Carro:* ${trip.vehicleLabel}`,`*Roteiro:* ${trip.route}`,`*Período:* ${date(trip.departureDate)} a ${date(trip.arrivalDate)}`,`*Litros solicitados:* ${liters[index]||''} L`,`*KM previsto:* ${kms[index]||''} km`,''));if(contacts.length)lines.push(`*Destinatários:* ${contacts.map(contact=>contact.name).join(', ')}`);return lines.join('\n')},[trips,contacts,liters,kms]);
 function openWhatsApp(){window.location.assign('https://wa.me/?text='+encodeURIComponent(text))}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><button type="button" onClick={()=>window.history.back()} className="mb-5 h-14 w-full rounded-xl border-2 border-slate-500 px-3 text-lg font-bold text-slate-700">Voltar para destinatários</button><section className="rounded-3xl border-2 border-[#096a9b] bg-white p-6 shadow"><h1 className="text-3xl font-bold">Solicitação pronta</h1><p className="mt-3 text-lg text-slate-600">Confira o texto. O próximo botão abre o WhatsApp uma única vez.</p><pre className="mt-5 whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 font-sans text-base">{text}</pre><button type="button" onClick={openWhatsApp} disabled={!!message||!trips.length} className="mt-5 min-h-14 h-auto w-full rounded-xl bg-[#178045] px-4 py-2 text-lg font-bold leading-tight text-white disabled:opacity-50 sm:text-xl">Abrir WhatsApp para enviar</button></section>{message&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{message}</p>}</div></main>
}
