import {env} from 'cloudflare:workers';
import {isAdmin,requireRole} from '../admin-auth';

export const dynamic='force-dynamic';
const dateOk=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value);
type TripInput={vehicleId:number;departureDate:string;arrivalDate:string;route:string;totalKm:number;associatedUserIds?:number[];allowConflicts?:boolean};
const rangeConflict=(vehicleId:number,departureDate:string,arrivalDate:string,excludeId?:number)=>env.DB!.prepare(`SELECT id FROM trips WHERE vehicle_id=? ${excludeId?'AND id<>?':''} AND COALESCE(departure_date,travel_date)<=? AND COALESCE(arrival_date,travel_date)>=? LIMIT 1`).bind(vehicleId,...(excludeId?[excludeId]:[]),arrivalDate,departureDate).first();
async function driverConflict(driverIds:number[],departureDate:string,arrivalDate:string,excludeId?:number){for(const driverId of driverIds){const row=await env.DB!.prepare(`SELECT t.id FROM trips t JOIN trip_users tu ON tu.trip_id=t.id WHERE tu.user_id=? ${excludeId?'AND t.id<>?':''} AND COALESCE(t.departure_date,t.travel_date)<=? AND COALESCE(t.arrival_date,t.travel_date)>=? LIMIT 1`).bind(driverId,...(excludeId?[excludeId]:[]),arrivalDate,departureDate).first();if(row)return true}return false}
function valid(input:TripInput){return Number.isInteger(input.vehicleId)&&dateOk(input.departureDate)&&dateOk(input.arrivalDate)&&input.arrivalDate>=input.departureDate&&typeof input.route==='string'&&!!input.route.trim()&&input.route.trim().length<=300&&Number.isSafeInteger(input.totalKm)&&input.totalKm>0&&Array.isArray(input.associatedUserIds)&&input.associatedUserIds.length<=3&&input.associatedUserIds.every(Number.isSafeInteger)}

export async function GET(req:Request){try{const url=new URL(req.url),vehicleId=Number(url.searchParams.get('vehicleId')),date=url.searchParams.get('date'),available=url.searchParams.get('available')==='1';const headers={'Cache-Control':'no-store, max-age=0'};if(vehicleId&&date){const trip=await env.DB!.prepare("SELECT id,vehicle_id AS vehicleId,COALESCE(departure_date,travel_date) AS departureDate,COALESCE(arrival_date,travel_date) AS arrivalDate,route,total_km AS totalKm FROM trips WHERE vehicle_id=? AND COALESCE(departure_date,travel_date)<=? AND COALESCE(arrival_date,travel_date)>=? ORDER BY COALESCE(departure_date,travel_date) DESC LIMIT 1").bind(vehicleId,date,date).first();return Response.json({trip:trip||null},{headers})}const access=await requireRole(req,'solicitante','autorizador','avisado');if(!access.user)return Response.json({error:access.error},{status:403,headers});const admin=access.user.roles.includes('admin');const requestedFilter=available?" WHERE NOT EXISTS (SELECT 1 FROM fuel_requests fr WHERE fr.trip_id=t.id)":'';const fields="t.id,t.vehicle_id AS vehicleId,v.label AS vehicleLabel,COALESCE(t.departure_date,t.travel_date) AS departureDate,COALESCE(t.arrival_date,t.travel_date) AS arrivalDate,t.route,t.total_km AS totalKm";const sql=admin?`SELECT ${fields},COALESCE(GROUP_CONCAT(tu.user_id), '') AS userIds FROM trips t JOIN vehicles v ON v.id=t.vehicle_id LEFT JOIN trip_users tu ON tu.trip_id=t.id${requestedFilter} GROUP BY t.id ORDER BY t.id DESC LIMIT 100`:`SELECT ${fields},COALESCE(GROUP_CONCAT(tu2.user_id), '') AS userIds FROM trips t JOIN vehicles v ON v.id=t.vehicle_id JOIN trip_users mine ON mine.trip_id=t.id AND mine.user_id=? LEFT JOIN trip_users tu2 ON tu2.trip_id=t.id${available?" WHERE NOT EXISTS (SELECT 1 FROM fuel_requests fr WHERE fr.trip_id=t.id)":""} GROUP BY t.id ORDER BY t.id DESC LIMIT 100`;const trips=admin?await env.DB!.prepare(sql).all():await env.DB!.prepare(sql).bind(access.user.id).all();return Response.json({trips:(trips.results||[]).map((trip:any)=>({...trip,userIds:trip.userIds?String(trip.userIds).split(',').map(Number):[]}))},{headers})}catch{return Response.json({error:'Não foi possível consultar as viagens.'},{status:503,headers:{'Cache-Control':'no-store, max-age=0'}})}}

export async function POST(req:Request){if(!await isAdmin(req))return Response.json({error:'Apenas o administrador pode lançar viagens.'},{status:403});try{const input=await req.json() as TripInput;if(!valid(input))return Response.json({error:'Confira veículo, datas, quilometragem total, roteiro e até três motoristas.'},{status:400});const selected=[...new Set(input.associatedUserIds||[])];const [vehicleBusy,driverBusy]=await Promise.all([rangeConflict(input.vehicleId,input.departureDate,input.arrivalDate),driverConflict(selected,input.departureDate,input.arrivalDate)]);if((vehicleBusy||driverBusy)&&!input.allowConflicts)return Response.json({error:'Já existe viagem para este carro ou motorista no período. Confirme a compatibilidade de horário antes de salvar.',conflicts:{vehicle:!!vehicleBusy,driver:driverBusy}},{status:409});const trip=await env.DB!.prepare('INSERT INTO trips (vehicle_id,travel_date,departure_date,arrival_date,route,total_km) VALUES (?,?,?,?,?,?) RETURNING id,vehicle_id AS vehicleId,departure_date AS departureDate,arrival_date AS arrivalDate,route,total_km AS totalKm').bind(input.vehicleId,input.departureDate,input.departureDate,input.arrivalDate,input.route.trim(),input.totalKm).first<{id:number}>();const automatic=await env.DB!.prepare("SELECT id FROM app_users WHERE active=1 AND group_name IN ('adm','gerencia')").all<{id:number}>();const userIds=[...new Set([...selected,...automatic.results.map(user=>user.id)])];if(trip&&userIds.length)await env.DB!.batch(userIds.map(userId=>env.DB!.prepare('INSERT OR IGNORE INTO trip_users (trip_id,user_id) VALUES (?,?)').bind(trip.id,userId)));return Response.json({trip})}catch{return Response.json({error:'Não foi possível salvar a viagem.'},{status:503})}}
