'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

type Named={id:number;label?:string;name?:string};
type Item={kind:string;quantity:string;amount:string};
type Record={id:number;vehicleId:number;vehicleLabel:string;driverId:number|null;driver:string;odometer:number;amountCents:number;createdAt:string;route?:string|null;items:{kind:string;quantity:number;amountCents:number}[]};
const types=['Gasolina','Diesel','ARLA 32','Diversos'];
const blank=():Item=>({kind:'',quantity:'',amount:''});
const num=(v:string)=>Number(v.replace(',','.'));
const cents=(v:string)=>Math.round(num(v)*100);
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);

export default function Home(){
 const [step,setStep]=useState(1),[vehicles,setVehicles]=useState<Named[]>([]),[drivers,setDrivers]=useState<Named[]>([]),[records,setRecords]=useState<Record[]>([]);
 const [vehicle,setVehicle]=useState(''),[driver,setDriver]=useState(''),[km,setKm]=useState(''),[items,setItems]=useState<Item[]>([blank()]),[itemIndex,setItemIndex]=useState(0),[editing,setEditing]=useState<number|null>(null);
 const [route,setRoute]=useState(''),[routeConfirmed,setRouteConfirmed]=useState(false),[routeEdit,setRouteEdit]=useState(false);
 const [adding,setAdding]=useState<'vehicle'|'driver'|null>(null),[newName,setNewName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[date,setDate]=useState(''),[saved,setSaved]=useState(false),[showRecords,setShowRecords]=useState(false),[vehicleOpen,setVehicleOpen]=useState(false),[driverOpen,setDriverOpen]=useState(false),[completion,setCompletion]=useState<'lançado'|'editado'>('lançado');
 const item=items[itemIndex]||blank();
 const total=items.reduce((s,i)=>s+(Number.isFinite(cents(i.amount))?cents(i.amount):0),0);
 async function load(){try{const a=await Promise.all(['/api/vehicles','/api/drivers','/api/fueling'].map(async u=>{const r=await fetch(u,{cache:'no-store'});return r.json() as Promise<any>}));setVehicles(a[0].vehicles||[]);setDrivers(a[1].drivers||[]);setRecords(a[2].records||[])}catch{setMessage('Não foi possível carregar os dados. Atualize a página.')}}
 async function showLast30(){try{const r=await fetch('/api/fueling?days=30',{cache:'no-store'}),x:any=await r.json();if(!r.ok)throw Error(x.error);setRecords(x.records||[]);setShowRecords(true);window.scrollTo({top:0,behavior:'smooth'})}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível carregar os abastecimentos.')}}
 useEffect(()=>{if(!vehicle)return;const d=new Date().toISOString().slice(0,10);fetch('/api/trips?vehicleId='+vehicle+'&date='+d).then(r=>r.json()).then((x:any)=>{setRoute(x.trip?.route||'');setRouteConfirmed(false);setRouteEdit(!x.trip)}).catch(()=>{setRoute('');setRouteEdit(true)})},[vehicle]);
 useEffect(()=>{setDate(new Intl.DateTimeFormat('pt-BR',{dateStyle:'full',timeZone:'America/Bahia'}).format(new Date()));void load()},[]);
 function change(field:keyof Item,value:string){setItems(a=>a.map((i,n)=>n===itemIndex?{...i,[field]:value}:i))}
 function validItem(){return !!item.kind&&Number.isFinite(num(item.quantity))&&num(item.quantity)>0&&Number.isFinite(num(item.amount))&&num(item.amount)>=0}
 function go(){if(step===1&&!vehicle)return setMessage('Escolha um veículo para continuar.');if(step===1&&!route.trim())return setMessage('Confirme ou informe o roteiro para continuar.');if(step===1&&!routeConfirmed)return setMessage('Confirme o roteiro para continuar.');if(step===2&&!driver)return setMessage('Escolha um motorista para continuar.');if(step===3&&(!Number.isSafeInteger(Number(km))||Number(km)<0))return setMessage('Informe a quilometragem do veículo.');if(step===5&&(!Number.isFinite(num(item.quantity))||num(item.quantity)<=0))return setMessage('Informe a quantidade.');if(step===6&&(!Number.isFinite(num(item.amount))||num(item.amount)<0))return setMessage('Informe o valor.');setMessage('');setStep(s=>Math.min(7,s+1));window.scrollTo({top:0,behavior:'smooth'})}
 function back(){setMessage('');setStep(s=>Math.max(1,s-1));window.scrollTo({top:0,behavior:'smooth'})}
 function addAnother(){if(!validItem())return setMessage('Complete o item antes de adicionar outro.');setItems(a=>[...a,blank()]);setItemIndex(items.length);setStep(4);setMessage('');window.scrollTo({top:0,behavior:'smooth'})}
 async function create(e:React.FormEvent){e.preventDefault();if(!adding||!newName.trim())return;setBusy(true);try{const isV=adding==='vehicle';const r=await fetch(isV?'/api/vehicles':'/api/drivers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(isV?{label:newName.trim()}:{name:newName.trim()})});const x:any=await r.json();if(!r.ok)throw Error(x.error);if(isV){setVehicles(a=>[...a,x.vehicle]);setVehicle(String(x.vehicle.id))}else{setDrivers(a=>[...a,x.driver]);setDriver(String(x.driver.id))}setAdding(null);setNewName('');setMessage('Cadastro concluído e selecionado.')}catch(e){setMessage(e instanceof Error?e.message:'Falha no cadastro.')}finally{setBusy(false)}}
 async function save(){const wasEditing=editing!==null;setBusy(true);try{const r=await fetch(editing?'/api/fueling/'+editing:'/api/fueling',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicleId:Number(vehicle),driverId:Number(driver),odometer:Number(km),items:items.map(i=>({kind:i.kind,quantity:num(i.quantity),amountCents:cents(i.amount)}))})});const x:any=await r.json();if(!r.ok)throw Error(x.error);reset();await load();setCompletion(wasEditing?'editado':'lançado');setMessage('');setSaved(true);window.scrollTo({top:0,behavior:'smooth'})}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}}
 function reset(){setStep(1);setVehicle('');setDriver('');setKm('');setItems([blank()]);setItemIndex(0);setEditing(null)}
 function edit(r:Record){if(!r.driverId){setMessage('Este registro antigo não possui motorista cadastrado para edição.');return}setEditing(r.id);setVehicle(String(r.vehicleId));setDriver(String(r.driverId));setKm(String(r.odometer));setItems(r.items.map(i=>({kind:i.kind,quantity:String(i.quantity),amount:(i.amountCents/100).toFixed(2).replace('.',',')})));setItemIndex(0);setStep(1);setMessage('Edite o registro confirmando cada etapa.');window.scrollTo({top:0,behavior:'smooth'})}
 function leave(){if(window.history.length>1){window.history.back();return}setSaved(false);setShowRecords(false);reset();setMessage('')}
 if(saved)return <main className="grid min-h-screen place-items-center bg-[#f3f6f9] px-5 py-10"><section className="w-full max-w-xl rounded-3xl border border-[#bfe0cc] bg-white p-8 text-center shadow-[0_12px_35px_rgba(22,64,91,.08)] sm:p-12"><p className="text-5xl text-[#178045]">✓</p><h1 className="mt-5 text-4xl font-extrabold leading-tight text-[#178045] sm:text-5xl">{completion==='editado'?'Edição concluída':'Abastecimento lançado'}</h1><p className="mt-4 text-xl text-[#526979]">{completion==='editado'?'As alterações foram salvas com sucesso.':'O registro foi salvo com sucesso.'}</p><div className="mt-10 grid gap-4"><Button type="button" onClick={()=>{setSaved(false);void showLast30()}} className="h-16 bg-[#178045] text-xl font-bold text-white">Listar meus abastecimentos</Button><Button type="button" onClick={leave} variant="outline" className="h-16 border-[#526979] text-xl font-bold text-[#102b43]">Sair</Button></div></section></main>;
 const heading=['Qual é o veículo?','Quem abasteceu?','Qual é a quilometragem?','O que foi comprado?','Qual foi a quantidade?','Qual foi o valor?','Confirme o abastecimento'][step-1];
 const showBack=step!==1&&step!==7; const showNext=step===1||step===2||step===3||step===4||step===5;
 return (<main className="min-h-screen bg-[#f3f6f9] px-4 py-6 sm:py-10"><div className="mx-auto max-w-xl"><header className="mb-4 flex items-center gap-3"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#103b58] text-2xl text-white">⛽</span><div><p className="text-base font-bold uppercase tracking-[.1em] text-[#096a9b]">Controle de frota</p><h1 className="text-3xl font-bold">Abastecimento</h1></div><a href="/admin" className="ml-auto rounded-xl border-2 border-[#096a9b] px-4 py-3 text-base font-bold text-[#096a9b]">Área Adm</a></header><Button type="button" onClick={()=>void showLast30()} variant="outline" className="mb-6 h-14 w-full border-[#096a9b] text-lg font-bold text-[#096a9b]">Meus abastecimentos</Button>
 <section className="rounded-3xl border border-[#d2e0e7] bg-white p-6 shadow-[0_12px_35px_rgba(22,64,91,.08)] sm:p-9"><div className="flex justify-between text-sm font-bold text-[#526979]"><span>Etapa {step} de 7</span><span>{heading}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#dbe8ee]"><div className="h-full rounded-full bg-[#096a9b]" style={{width:(step/7*100)+'%'}}/></div><p className="mt-5 text-lg capitalize text-[#526979]">{date}</p>
 <h2 className="mt-3 text-3xl font-bold">{heading}</h2>
 {step===1&&<div><p className="mt-2 text-lg text-[#526979]">Selecione o carro que foi abastecido.</p><button type="button" aria-expanded={vehicleOpen} onClick={()=>setVehicleOpen(open=>!open)} className="mt-7 flex h-16 w-full items-center justify-between rounded-xl border-2 border-[#d2e0e7] bg-white px-4 text-left text-lg font-bold text-[#102b43] outline-none focus:border-[#096a9b]"><span>{vehicles.find(v=>String(v.id)===vehicle)?.label||'Escolher veículo'}</span><span aria-hidden="true" className="text-2xl">⌄</span></button>{vehicleOpen&&<div role="listbox" aria-label="Veículos" className="mt-2 max-h-72 overflow-y-auto rounded-xl border-2 border-[#d2e0e7] bg-white p-2 shadow-lg">{vehicles.length===0?<p className="p-3 text-lg text-[#526979]">Nenhum veículo cadastrado.</p>:vehicles.map(v=><button type="button" role="option" aria-selected={vehicle===String(v.id)} key={v.id} onClick={()=>{setVehicle(String(v.id));setVehicleOpen(false)}} className="block w-full rounded-lg px-4 py-4 text-left text-xl font-bold text-[#102b43] active:bg-[#eaf6fa]">{v.label}</button>)}</div>}<button type="button" onClick={()=>setAdding('vehicle')} className="mt-5 text-lg font-bold text-[#096a9b] underline">+ Cadastrar novo veículo</button>{vehicle&&<div className="mt-6 rounded-2xl border-2 border-[#096a9b] bg-[#eaf6fa] p-5"><p className="text-lg font-bold text-[#075579]">Roteiro previsto para hoje</p>{routeEdit?<><Input value={route} onChange={e=>{setRoute(e.target.value);setRouteConfirmed(false)}} placeholder="Digite o novo roteiro" className="mt-3 h-16 !text-xl"/><Button type="button" onClick={()=>setRouteConfirmed(true)} className="mt-3 h-12 bg-[#096a9b] text-base text-white">Confirmar roteiro</Button></>:<><p className="mt-2 text-2xl font-bold">{route||'Sem roteiro lançado'}</p><p className="mt-3 text-lg font-bold">Confirma este roteiro?</p><div className="mt-3 flex gap-3"><Button type="button" onClick={()=>setRouteConfirmed(true)} className="h-12 bg-[#178045] text-base text-white">Sim</Button><Button type="button" onClick={()=>{setRouteEdit(true);setRouteConfirmed(false)}} className="h-12 bg-[#e7b629] text-base text-[#2c2509]">Não, alterar</Button></div></>}</div>}</div>}
 {step===2&&<div><p className="mt-2 text-lg text-[#526979]">Selecione o motorista responsável.</p><button type="button" aria-expanded={driverOpen} onClick={()=>setDriverOpen(open=>!open)} className="mt-7 flex h-16 w-full items-center justify-between rounded-xl border-2 border-[#d2e0e7] bg-white px-4 text-left text-lg font-bold text-[#102b43] outline-none focus:border-[#096a9b]"><span>{drivers.find(d=>String(d.id)===driver)?.name||'Escolher motorista'}</span><span aria-hidden="true" className="text-2xl">⌄</span></button>{driverOpen&&<div role="listbox" aria-label="Motoristas" className="mt-2 max-h-72 overflow-y-auto rounded-xl border-2 border-[#d2e0e7] bg-white p-2 shadow-lg">{drivers.length===0?<p className="p-3 text-lg text-[#526979]">Nenhum motorista cadastrado.</p>:drivers.map(d=><button type="button" role="option" aria-selected={driver===String(d.id)} key={d.id} onClick={()=>{setDriver(String(d.id));setDriverOpen(false)}} className="block w-full rounded-lg px-4 py-4 text-left text-xl font-bold text-[#102b43] active:bg-[#eaf6fa]">{d.name}</button>)}</div>}<button type="button" onClick={()=>setAdding('driver')} className="mt-5 text-lg font-bold text-[#096a9b] underline">+ Cadastrar novo motorista</button></div>}
 {step===3&&<div><p className="mt-2 text-lg text-[#526979]">Informe o KM mostrado no painel.</p><Input autoFocus type="number" inputMode="numeric" min="0" value={km} onChange={e=>setKm(e.target.value)} placeholder="Ex.: 85.420" className="mt-7 h-16 !text-2xl"/></div>}
 {step===4&&<div><p className="mt-2 text-lg text-[#526979]">Item {itemIndex+1} do abastecimento.</p><div className="mt-7 grid gap-3">{types.map(t=><button key={t} onClick={()=>{change('kind',t);setStep(5)}} className="h-16 rounded-2xl border-2 border-[#d2e0e7] bg-white px-5 text-left text-xl font-bold hover:border-[#096a9b]">{t}</button>)}</div></div>}
 {step===5&&<div><p className="mt-2 text-lg text-[#526979]">Produto: <strong>{item.kind}</strong></p><Input autoFocus inputMode="decimal" value={item.quantity} onChange={e=>change('quantity',e.target.value)} placeholder="Ex.: 40,50" className="mt-7 h-16 !text-2xl"/></div>}
 {step===6&&<div><p className="mt-2 text-lg text-[#526979]">{item.kind}: {item.quantity}</p><Input autoFocus inputMode="decimal" value={item.amount} onChange={e=>change('amount',e.target.value)} placeholder="Ex.: 250,00" className="mt-7 h-16 !text-2xl"/><p className="mt-3 text-lg text-[#526979]">Digite o valor total deste item em reais.</p></div>}
 {step===7&&<div><div className="mt-6 space-y-3 rounded-2xl bg-[#edf5f9] p-5 text-lg"><p><strong>Veículo:</strong> {vehicles.find(v=>String(v.id)===vehicle)?.label}</p><p><strong>Motorista:</strong> {drivers.find(d=>String(d.id)===driver)?.name}</p><p><strong>KM:</strong> {Number(km).toLocaleString('pt-BR')}</p><div className="border-t border-[#c9dfe9] pt-3">{items.map((i,n)=><p key={n}>{i.kind} · {i.quantity} · <strong>{money(cents(i.amount))}</strong></p>)}</div><p className="text-2xl font-bold">Total: {money(total)}</p></div><div className="mt-6 rounded-2xl border border-[#c9dfe9] p-4"><p className="text-lg font-bold">Há outro item?</p><div className="mt-3 flex gap-3"><Button type="button" onClick={addAnother} variant="outline" className="h-13 border-[#096a9b] text-base text-[#096a9b]">Sim, adicionar</Button><Button type="button" onClick={()=>setStep(7)} className="h-13 bg-[#096a9b] text-base text-white">Não, salvar</Button></div></div></div>}
 {adding&&<div className="mt-7 rounded-2xl border border-[#b8d6e3] bg-[#eff7fa] p-5"><h3 className="text-xl font-bold">Cadastrar {adding==='vehicle'?'veículo':'motorista'}</h3><form onSubmit={create} className="mt-4 space-y-3"><Input autoFocus value={newName} onChange={e=>setNewName(e.target.value)} placeholder={adding==='vehicle'?'Número ou placa':'Nome completo'} className="h-14 !text-lg"/><div className="flex gap-3"><Button disabled={busy} className="h-12 bg-[#096a9b] text-base text-white">Cadastrar</Button><Button type="button" onClick={()=>setAdding(null)} variant="outline" className="h-12 text-base">Cancelar</Button></div></form></div>}
 {message&&<p role="status" className="mt-6 rounded-xl bg-[#e9f5f7] p-4 text-lg font-medium">{message}</p>}
 <div className="mt-9 flex gap-3">{showBack&&<Button type="button" onClick={back} variant="outline" className="h-14 text-lg">Voltar</Button>}{showNext&&<Button type="button" onClick={go} className="h-14 flex-1 bg-[#096a9b] text-lg font-bold text-white">Continuar</Button>}{step===6&&<Button type="button" onClick={go} className="h-14 flex-1 bg-[#096a9b] text-lg font-bold text-white">Concluir item</Button>}{step===7&&<div className="contents"><Button type="button" onClick={back} variant="outline" className="h-14 text-lg">Voltar</Button><Button type="button" disabled={busy} onClick={save} className="h-14 flex-1 bg-[#178045] text-lg font-bold text-white">Salvar</Button></div>}</div></section>
 {showRecords&&<section className="mt-7 rounded-3xl border border-[#d2e0e7] bg-white p-6 shadow-[0_12px_35px_rgba(22,64,91,.08)]"><div className="flex items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">Meus abastecimentos</h2><p className="mt-1 text-lg text-[#526979]">Últimos 30 dias</p></div><Button type="button" onClick={()=>setShowRecords(false)} variant="outline" className="text-base">Fechar</Button></div>{records.length===0?<p className="mt-5 text-lg text-[#526979]">Nenhum abastecimento nos últimos 30 dias.</p>:<div className="mt-5 space-y-4">{records.map(r=><article key={r.id} className="rounded-2xl bg-[#edf5f9] p-5"><p className="text-lg text-[#526979]"><strong>Data:</strong> {new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Bahia'}).format(new Date(r.createdAt))}</p><p className="mt-2 text-xl font-bold"><strong>Carro:</strong> {r.vehicleLabel}</p><p className="mt-2 text-lg"><strong>Roteiro:</strong> {r.route||'Não informado'}</p><p className="mt-2 text-xl font-bold text-[#178045]"><strong>Valor total:</strong> {money(r.amountCents)}</p><div className="mt-4"><Button type="button" onClick={()=>{setShowRecords(false);edit(r)}} className="bg-[#e7b629] text-[#2c2509]">Editar</Button></div></article>)}</div>}</section>}
 </div></main>)
}
