import { env } from 'cloudflare:workers';
import { validate } from './common';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{
 const last30=new URL(req.url).searchParams.get('days')==='30';
 const sql=last30?'SELECT f.id,f.vehicle_id AS vehicleId,v.label AS vehicleLabel,f.driver_id AS driverId,f.driver,f.odometer,f.amount_cents AS amountCents,f.created_at AS createdAt,f.liters,(SELECT t.route FROM trips t WHERE t.vehicle_id=f.vehicle_id AND date(f.created_at) BETWEEN COALESCE(t.departure_date,t.travel_date) AND COALESCE(t.arrival_date,t.travel_date) ORDER BY COALESCE(t.departure_date,t.travel_date) DESC LIMIT 1) AS route FROM fueling f JOIN vehicles v ON v.id=f.vehicle_id WHERE f.created_at>=datetime(\'now\',\'-30 days\') ORDER BY f.created_at DESC,f.id DESC':'SELECT f.id,f.vehicle_id AS vehicleId,v.label AS vehicleLabel,f.driver_id AS driverId,f.driver,f.odometer,f.amount_cents AS amountCents,f.created_at AS createdAt,f.liters,(SELECT t.route FROM trips t WHERE t.vehicle_id=f.vehicle_id AND date(f.created_at) BETWEEN COALESCE(t.departure_date,t.travel_date) AND COALESCE(t.arrival_date,t.travel_date) ORDER BY COALESCE(t.departure_date,t.travel_date) DESC LIMIT 1) AS route FROM fueling f JOIN vehicles v ON v.id=f.vehicle_id ORDER BY f.created_at DESC,f.id DESC LIMIT 50';
 const records=(await env.DB!.prepare(sql).all()).results;
 const ids=records.map(r=>Number(r.id));const items=ids.length?(await env.DB!.prepare(`SELECT fueling_id AS fuelingId,kind,quantity,amount_cents AS amountCents FROM fueling_items WHERE fueling_id IN (${ids.map(()=>'?').join(',')}) ORDER BY id`).bind(...ids).all()).results:[];
 return Response.json({records:records.map(r=>({...r,items:items.filter(i=>i.fuelingId===r.id)}))});
 }catch{return Response.json({error:'Não foi possível carregar os registros.'},{status:503})}}
export async function POST(req:Request){try{const data=await validate(await req.json());if(!data)return Response.json({error:'Confira veículo, motorista, KM, itens, quantidades e valores.'},{status:400});const duplicate=await env.DB!.prepare('SELECT id FROM fueling WHERE vehicle_id=? AND odometer=? LIMIT 1').bind(data.vehicleId,data.odometer).first();if(duplicate)return Response.json({error:'Já existe um abastecimento deste veículo com esta quilometragem. Confira o KM informado.'},{status:409});const id=Date.now()*1000+Math.floor(Math.random()*1000);const date=new Date().toISOString();await env.DB!.batch([env.DB!.prepare('INSERT INTO fueling (id,vehicle_id,driver_id,driver,liters,odometer,amount_cents,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,data.vehicleId,data.driverId,data.driverName,data.liters,data.odometer,data.total,date),...data.items.map(i=>env.DB!.prepare('INSERT INTO fueling_items (fueling_id,kind,quantity,amount_cents) VALUES (?,?,?,?)').bind(id,i.kind,i.quantity,i.amountCents))]);return Response.json({id,createdAt:date},{status:201})}catch{return Response.json({error:'Falha ao salvar. Tente novamente.'},{status:503})}}
