'use client';
import {useEffect,useMemo,useState} from 'react';

type Trip={id:number;vehicleId:number;vehicleLabel:string;departureDate:string;arrivalDate:string;route:string};
const formatDate=(date:string)=>date.split('-').reverse().join('/');

export default function SolicitarAbastecimento(){
 const [trips,setTrips]=useState<Trip[]>([]),[vehicle,setVehicle]=useState(''),[message,setMessage]=useState('Carregando viagens...');
 useEffect(()=>{void (async()=>{try{const response=await fetch('/api/trips?available=1',{cache:'no-store'}),data:any=await response.json();if(!response.ok){setMessage(data.error||'Não foi possível carregar as viagens.');return}setTrips(data.trips||[]);setMessage('')}catch{setMessage('Não foi possível carregar as viagens. Atualize a página e tente novamente.')}})()},[]);
 const vehicles=useMemo(()=>{const seen=new Map<number,string>();trips.forEach(trip=>seen.set(trip.vehicleId,trip.vehicleLabel));return [...seen].map(([id,label])=>({id,label})).sort((a,b)=>a.label.localeCompare(b.label,'pt-BR'));},[trips]);
 const vehicleTrips=trips.filter(trip=>String(trip.vehicleId)===vehicle);
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><button type="button" onClick={()=>window.location.assign('/lancar-abastecimento')} className="mb-5 h-14 w-full rounded-xl border-2 border-slate-500 bg-white px-3 text-lg font-bold text-slate-700">Voltar</button><section className="rounded-3xl border-2 border-[#178045] bg-white p-6 shadow"><h1 className="text-3xl font-extrabold">Solicitar abastecimento</h1><p className="mt-3 text-lg text-slate-600">Escolha o carro e depois a viagem que ainda está dentro do período e não possui solicitação.</p>{!message&&<><label className="mt-6 block text-lg font-bold">1. Selecione o carro<select value={vehicle} onChange={event=>setVehicle(event.target.value)} className="mt-2 h-16 w-full rounded-xl border-2 border-slate-300 bg-white p-3 text-xl"><option value="">Escolher veículo</option>{vehicles.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>{vehicle&&<form action="/solicitar-abastecimento/detalhes" method="get" className="mt-6 space-y-3"><p className="text-lg font-bold">2. Selecione a viagem</p>{vehicleTrips.length===0?<p className="rounded-xl bg-slate-50 p-4 text-lg">Não há viagem disponível para este veículo.</p>:vehicleTrips.map(trip=><label key={trip.id} className="flex cursor-pointer items-start gap-4 rounded-2xl border-2 border-slate-200 bg-white p-4 text-lg"><input name="trip" value={trip.id} type="checkbox" className="mt-1 h-6 w-6 shrink-0 accent-[#178045]"/><span><strong>{trip.route}</strong><br/><small>Saída: {formatDate(trip.departureDate)} · Chegada: {formatDate(trip.arrivalDate)}</small></span></label>)}<button type="submit" className="mt-3 min-h-14 h-auto w-full rounded-xl bg-[#178045] px-4 py-2 text-lg font-bold leading-tight text-white sm:text-xl">Enviar solicitação</button></form>}</>}{message&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{message}</p>}{!message&&!vehicles.length&&<p className="mt-5 rounded-xl bg-slate-50 p-4 text-lg">Não há viagens disponíveis. Viagens já solicitadas ou encerradas não aparecem nesta lista.</p>}</section></div></main>;
}
