'use client';

import {useEffect,useState} from 'react';
import {Car,FilePenLine,Plus,Trash2} from 'lucide-react';

type Vehicle={id:number;label:string};

export default function CadastroCarros(){
 const [vehicles,setVehicles]=useState<Vehicle[]>([]),[label,setLabel]=useState(''),[editing,setEditing]=useState<number|null>(null),[deleting,setDeleting]=useState<number|null>(null),[message,setMessage]=useState('');
 async function load(){const response=await fetch('/api/vehicles',{cache:'no-store'}),data:any=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível carregar os veículos.');setVehicles(data.vehicles||[]);}
 useEffect(()=>{void load().catch((error:Error)=>setMessage(error.message));},[]);
 function clear(){setLabel('');setEditing(null);setDeleting(null);}
 async function save(event:React.FormEvent){event.preventDefault();const response=await fetch(editing?`/api/vehicles/${editing}`:'/api/vehicles',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label})}),data:any=await response.json();if(!response.ok){setMessage(data.error||'Não foi possível salvar o veículo.');return;}const changed=editing!==null;clear();await load();setMessage(changed?'Veículo atualizado com sucesso.':'Veículo cadastrado com sucesso.');window.scrollTo({top:0,behavior:'smooth'});}
 function edit(vehicle:Vehicle){setLabel(vehicle.label);setEditing(vehicle.id);setDeleting(null);setMessage(`Editando ${vehicle.label}.`);window.scrollTo({top:0,behavior:'smooth'});}
 async function remove(vehicle:Vehicle){const response=await fetch(`/api/vehicles/${vehicle.id}`,{method:'DELETE'}),data:any=await response.json();if(!response.ok){setMessage(data.error||'Não foi possível apagar o veículo.');return;}if(editing===vehicle.id)clear();setDeleting(null);await load();setMessage('Veículo apagado.');}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><button type="button" onClick={()=>window.location.assign('/admin/configuracoes')} className="mb-5 min-h-12 rounded-xl border px-5 py-2 text-lg font-bold">Voltar para Configurações</button><section className="rounded-3xl bg-white p-6 shadow"><header className="flex items-center gap-3"><Car className="h-10 w-10 text-[#0b7184]"/><div><h1 className="text-3xl font-extrabold">Cadastro de carros</h1><p className="mt-1 text-lg text-slate-600">Cadastre e mantenha os veículos disponíveis no app.</p></div></header><form onSubmit={save} className="mt-6 space-y-4"><label className="block text-lg font-bold">Número, nome ou placa do veículo<input required value={label} onChange={event=>setLabel(event.target.value)} placeholder="Ex.: Carro 31000 ou ABC1D23" className="mt-2 h-14 w-full rounded-xl border p-3 text-lg"/></label><div className="flex gap-3"><button className="flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-[#0b7184] px-3 py-2 text-lg font-bold text-white">{editing?<FilePenLine className="h-6 w-6"/>:<Plus className="h-6 w-6"/>}{editing?'Salvar alterações':'Cadastrar carro'}</button>{editing&&<button type="button" onClick={()=>{clear();setMessage('Edição cancelada.');}} className="min-h-12 rounded-xl border px-4 py-2 text-lg font-bold">Cancelar</button>}</div></form>{message&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{message}</p>}<div className="mt-8 border-t pt-6"><h2 className="text-2xl font-extrabold">Carros cadastrados</h2>{vehicles.length===0?<p className="mt-4 rounded-xl bg-slate-50 p-4 text-lg text-slate-600">Nenhum carro cadastrado.</p>:<div className="mt-4 space-y-3">{vehicles.map(vehicle=><article key={vehicle.id} className="rounded-xl bg-slate-50 p-4"><p className="text-xl font-bold text-slate-900">{vehicle.label}</p>{deleting===vehicle.id?<div className="mt-3 rounded-xl border-2 border-[#b3262b] bg-red-50 p-3"><p className="font-bold text-[#7f1d1d]">Deseja apagar este veículo?</p><div className="mt-3 flex gap-3"><button type="button" onClick={()=>void remove(vehicle)} className="min-h-10 rounded-lg bg-[#b3262b] px-4 py-2 font-bold text-white">Confirmar apagar</button><button type="button" onClick={()=>setDeleting(null)} className="min-h-10 rounded-lg border px-4 py-2 font-bold">Cancelar</button></div></div>:<div className="mt-3 flex flex-wrap gap-3"><button type="button" onClick={()=>edit(vehicle)} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-[#e7b629] px-4 py-2 font-bold text-[#2c2509]"><FilePenLine className="h-5 w-5"/>Editar</button><button type="button" onClick={()=>setDeleting(vehicle.id)} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-[#b3262b] px-4 py-2 font-bold text-white"><Trash2 className="h-5 w-5"/>Apagar</button></div>}</article>)}</div>}</div></section></div></main>;
}
