'use client';

import {useEffect,useState} from 'react';

type Trip={id:number;vehicleId:number;vehicleLabel:string;departureDate:string;arrivalDate:string;route:string;totalKm:number;totalValueCents:number;userIds:number[]};
const draftKey='sd-tour-solicitacao-multipla-rascunho';
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value/100);
const decimal=(value:string)=>Number(value.trim().replace(/\./g,'').replace(',','.'));

export default function EditarViagemDoPedido(){
 const [trip,setTrip]=useState<Trip|null>(null),[value,setValue]=useState(''),[km,setKm]=useState(''),[message,setMessage]=useState('Carregando viagem...'),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 const returnTo=()=>{try{const draft=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(typeof draft?.returnUrl==='string'&&draft.returnUrl.startsWith('/solicitar-abastecimento/detalhes'))return draft.returnUrl}catch{}return '/solicitar-abastecimento'};
 useEffect(()=>{void (async()=>{const id=Number(new URLSearchParams(window.location.search).get('trip'));if(!Number.isSafeInteger(id)){setMessage('Viagem inválida.');return}try{const response=await fetch('/api/trips',{cache:'no-store'}),data:any=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível carregar a viagem.');const found=(data.trips||[]).find((item:Trip)=>item.id===id);if(!found)throw Error('Viagem não encontrada ou sem permissão para edição.');setTrip(found);setKm(String(found.totalKm||''));setValue(((found.totalValueCents||0)/100).toFixed(2).replace('.',','));setMessage('')}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível carregar a viagem.')}})()},[]);
 async function save(){if(!trip)return;const total=Math.round(decimal(value)*100),totalKm=Number(km);if(!Number.isSafeInteger(totalKm)||totalKm<=0||!Number.isSafeInteger(total)||total<=0){setMessage('Informe quilometragem e valor total válidos.');return}setSaving(true);setMessage('');try{const response=await fetch(`/api/trips/${trip.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicleId:trip.vehicleId,departureDate:trip.departureDate,arrivalDate:trip.arrivalDate,route:trip.route,totalKm,totalValueCents:total,associatedUserIds:trip.userIds||[],allowConflicts:true})}),data:any=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível salvar a viagem.');setTrip({...trip,totalKm,totalValueCents:total});setSaved(true)}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível salvar a viagem.')}finally{setSaving(false)}}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><section className="rounded-3xl border-2 border-[#e7b629] bg-white p-6 shadow"><h1 className="text-3xl font-extrabold">Editar viagem</h1><p className="mt-3 text-lg text-slate-600">A correção é feita somente nesta viagem. As demais solicitações continuam guardadas.</p>{trip&&<><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-xl font-bold">{trip.vehicleLabel}</p><p className="mt-1 text-lg">{trip.route}</p><p className="mt-2 text-base text-slate-600">{trip.departureDate.split('-').reverse().join('/')} a {trip.arrivalDate.split('-').reverse().join('/')}</p></div><label className="mt-5 block text-lg font-bold">Quilometragem total<input type="number" inputMode="numeric" min="1" value={km} onChange={event=>setKm(event.target.value)} className="mt-2 h-14 w-full rounded-xl border p-3 text-xl"/></label><label className="mt-5 block text-lg font-bold">Valor total da viagem (R$)<input inputMode="decimal" value={value} onChange={event=>setValue(event.target.value)} className="mt-2 h-14 w-full rounded-xl border p-3 text-xl"/><span className="mt-2 block text-base font-normal text-slate-600">Valor atual: {money(Number(trip.totalValueCents||0))}</span></label></>}{saved?<div className="mt-6"><p className="rounded-xl bg-green-50 p-4 text-lg font-bold text-[#178045]">Viagem corrigida com sucesso.</p><button type="button" onClick={()=>window.location.assign(returnTo())} className="mt-5 min-h-14 w-full rounded-xl bg-[#178045] px-4 py-2 text-lg font-extrabold text-white">Voltar ao pedido de abastecimento</button></div>:<button type="button" disabled={!trip||saving} onClick={()=>void save()} className="mt-6 min-h-14 w-full rounded-xl bg-[#e7b629] px-4 py-2 text-lg font-extrabold text-[#2c2509] disabled:opacity-50">{saving?'Salvando...':'Salvar correção da viagem'}</button>}{message&&<p role="status" className="mt-5 rounded-xl bg-red-50 p-4 text-lg text-[#b3262b]">{message}</p>}<button type="button" onClick={()=>window.location.assign(returnTo())} className="mt-4 min-h-12 w-full rounded-xl border-2 border-slate-500 px-4 py-2 text-base font-bold text-slate-700">Cancelar e voltar ao pedido</button></section></div></main>
}
