'use client';
import {useEffect,useState} from 'react';

type Notice={id:number;title:string;message:string;href:string;readAt:string|null;createdAt:string};
type Request={id:number;status:'pending'|'authorized';departureDate:string;arrivalDate:string;vehicleLabel:string;route:string;requestedBy:string;createdAt:string;authorizedBy:string;authorizedAt:string|null};
type Item={notice:Notice;request?:Request};
const requestId=(href:string)=>{const value=new URLSearchParams(href.split('?')[1]||'').get('pedido');return value?Number(value):NaN};
const today=()=>{const parts=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Bahia',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=(type:string)=>parts.find(part=>part.type===type)?.value||'';return `${value('year')}-${value('month')}-${value('day')}`};
const when=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Bahia'}).format(new Date(value));

export default function Avisos(){
 const [items,setItems]=useState<Item[]>([]),[message,setMessage]=useState('Carregando avisos...');
 useEffect(()=>{void Promise.all([fetch('/api/notifications',{cache:'no-store'}).then(r=>r.json()),fetch('/api/fuel-requests',{cache:'no-store'}).then(r=>r.json())]).then(([notices,requests])=>{
   const byId=new Map<number,Request>((requests.requests||[]).map((request:Request)=>[request.id,request]));
   const latest=new Map<string,Item>();
   for(const notice of notices.notifications||[]){const id=requestId(notice.href);const request=byId.get(id);if(Number.isInteger(id)&&id>0&&!request)continue;if(request&&request.departureDate<today())continue;const key=request?`request:${request.id}`:`notice:${notice.id}`;if(!latest.has(key))latest.set(key,{notice,request});}
   setItems([...latest.values()]);setMessage('');
 }).catch(()=>setMessage('Não foi possível carregar os avisos.'))},[]);
 async function open(item:Item){await fetch('/api/notifications',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.notice.id})});window.location.assign(item.notice.href)}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><button onClick={()=>window.location.assign('/')} className="mb-5 h-12 rounded-xl border px-5 text-lg font-bold">Página inicial</button><section className="rounded-3xl bg-white p-6 shadow"><h1 className="text-3xl font-bold">Meus avisos</h1><p className="mt-2 text-lg text-slate-600">Somente viagens futuras com pedido de abastecimento aparecem aqui.</p>{!message&&items.length===0?<p className="mt-5 rounded-xl bg-slate-50 p-4 text-lg">Nenhum aviso de viagem futura no momento.</p>:<div className="mt-5 space-y-4">{items.map(({notice,request})=>{const pending=request?.status==='pending';const authorized=request?.status==='authorized';return <button key={request?`request-${request.id}`:notice.id} onClick={()=>void open({notice,request})} className={`w-full overflow-hidden rounded-2xl border-2 text-left shadow-sm transition active:scale-[0.99] ${pending?'border-red-300 bg-white':authorized?'border-green-400 bg-white':'border-[#096a9b] bg-white'}`}><div className="p-4"><div className="flex items-start gap-3">{authorized&&<span className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-[#178045] text-4xl font-black text-white">✓</span>}<div className="min-w-0"><p className="text-xl font-extrabold">{authorized?'Abastecimento autorizado':notice.title}</p>{request?<><p className="mt-2 text-lg font-bold">{request.vehicleLabel} · {request.route}</p><p className="mt-1 text-base">Solicitado por {request.requestedBy} em {when(request.createdAt)}</p>{authorized&&<p className="mt-1 text-base">Autorizado por {request.authorizedBy} em {request.authorizedAt?when(request.authorizedAt):'horário não informado'}</p>}</>:<p className="mt-1 text-lg">{notice.message}</p>}</div></div></div>{pending&&<div className="bg-[#b42318] px-4 py-4 text-white"><p className="text-xl font-extrabold">PENDENTE DE AUTORIZAÇÃO</p><p className="mt-1 text-base font-semibold">Aguardando autorização. Toque para acompanhar.</p></div>}{authorized&&<div className="bg-[#178045] px-4 py-4 text-white"><p className="text-xl font-extrabold">✓ ABASTECIMENTO AUTORIZADO</p><p className="mt-1 text-base font-semibold">A autorização foi concluída.</p></div>}{!request&&<p className="border-t px-4 py-3 text-sm text-slate-600">{when(notice.createdAt)}</p>}</button>})}</div>}</section>{message&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{message}</p>}</div></main>
}
