'use client';

import {useEffect,useState} from 'react';

type Fueling={id:number;vehicleLabel:string;route:string;driver:string;createdAt:string;amountCents:number;liters:number;authorizedBy:string;authorizedAt:string|null};
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value/100);
const dateTime=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Bahia'}).format(new Date(value));

export default function AbastecimentosFeitos(){
 const [items,setItems]=useState<Fueling[]>([]),[message,setMessage]=useState('Carregando abastecimentos...');
 async function load(){const response=await fetch('/api/admin/fueling-completed',{cache:'no-store'}),data:any=await response.json();if(response.status===403){window.location.assign('/admin?next='+encodeURIComponent('/admin/abastecimentos-feitos'));return}if(!response.ok)throw Error(data.error);setItems(data.fueling||[]);setMessage('')}
 useEffect(()=>{void (async()=>{try{const setup=await fetch('/api/system/setup',{method:'POST'});if(!setup.ok)throw Error('Não foi possível preparar os dados do app.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível carregar os abastecimentos.')}})()},[]);
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-xl"><div className="mb-5 grid grid-cols-2 gap-3"><button type="button" onClick={()=>window.location.assign('/admin')} className="h-14 rounded-xl border-2 border-slate-500 px-3 text-base font-bold text-slate-700 sm:text-lg">Voltar para Adm</button><button type="button" onClick={()=>void load()} className="h-14 rounded-xl border-2 border-[#096a9b] px-3 text-base font-bold text-[#096a9b] sm:text-lg">Atualizar lista</button></div><section className="rounded-3xl bg-white p-6 shadow"><h1 className="text-3xl font-bold">Abastecimentos feitos</h1><p className="mt-2 text-lg text-slate-600">Registros ligados à viagem, ao pedido e à autorização.</p>{!message&&items.length===0?<p className="mt-6 rounded-2xl bg-slate-50 p-5 text-lg text-slate-600">Nenhum abastecimento ligado a uma viagem foi lançado ainda.</p>:<div className="mt-6 space-y-4">{items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="text-xl font-extrabold text-[#102b43]">{item.vehicleLabel}</p><p className="mt-2 text-lg"><strong>Rota:</strong> {item.route}</p><p className="mt-2 text-lg"><strong>Motorista:</strong> {item.driver}</p><p className="mt-2 text-lg"><strong>Abastecimento feito:</strong> {dateTime(item.createdAt)}</p><p className="mt-2 text-lg"><strong>Litros:</strong> {Number(item.liters||0).toLocaleString('pt-BR')} L</p><p className="mt-2 text-xl font-extrabold text-[#178045]"><strong>Valor:</strong> {money(item.amountCents)}</p><p className="mt-3 rounded-xl bg-[#eaf6fa] p-3 text-lg"><strong>Autorizou:</strong> {item.authorizedBy}{item.authorizedAt?` em ${dateTime(item.authorizedAt)}`:' — sem autorização registrada'}</p></article>)}</div>}</section>{message&&<p role="status" className="mt-5 rounded-xl bg-sky-50 p-4 text-lg">{message}</p>}</div></main>
}
